version: 2

sources:
  - name: raw
    description: "Raw data layer"
    schema: raw
    tables:
      - name: csv_customers
        description: "Raw customer data from CSV with data quality issues"
        columns:
          - name: customer_id
          - name: email
          - name: first_name
          - name: last_name
          - name: phone
          - name: created_at
